before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - freebsd
    - linux
    - netbsd
    - openbsd
    - windows
  goarch:
    - amd64
    - arm
    - arm64
archive:
  wrap_in_directory: true
checksum:
  name_template: 'SHA256SUMS'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
